version: "3.5"

services:
  postgres:
    image: postgres:15.3-alpine3.18
    container_name: tic-tac-toe_postgress
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
